version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"    # REST
      - "8080:8080"    # WebSocket
    volumes:
      - ./.env-docker:/usr/src/app/.env:ro
      - ./src:/usr/src/app/src:ro
      - ./tsconfig.json:/usr/src/app/tsconfig.json:ro
    command: npm start
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env # POSTGRES_USER;POSTGRES_PASSWORD;POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: